### ISSUE TITLE
Add script for building debs for any gtk/icon theme source

### ISSUE THREAD

**Issue by jalfonsi** [regolith-linux/regolith-scripts#1]
Given the huge amount of themes and icons available in OpenDesktop, it would be nice to have them packaged at once. Usually icons or themes are installed in /usr/share/themes or icons. One would need a script which takes anyicon/gtk theme source tarball as input and creates a debian folder inside with minimal set of dependencies and then launches dpkg-buildpackage. I'll be happy to test it.

**Comment by kgilmer** [comment]
Did you mean to add this issue to https://github.com/regolith-linux/speed-ricer @jalfonsi?

**Comment by jalfonsi** [comment]
Ok, sorry but I didn't know if it was the right place.

**Comment by jalfonsi** [comment]
Just moved issue to https://github.com/regolith-linux/speed-ricer

**Comment by kgilmer** [comment]
No worries @jalfonsi and thanks for moving the issue. :smile:  This repo is for Regolith user scripts, whereas speed ricer is for general purpose deb packages that are DE agnostic.
